---
- name: Créer un utilisateur dans PostgreSQL
  hosts: all
  become: true

  vars:
    postgres_user: "mayssa"
    postgres_password: "mayssa"

  tasks:
    - name: Création de l'utilisateur dans PostgreSQL
      postgresql_user:
        db: my_database
        name: "{{ postgres_user }}"
        password: "{{ postgres_password }}"
        priv: ALL
